### ISSUE TITLE
Add links

### ISSUE THREAD

**Issue by MizouziE** [MizouziE/MizouziE.github.io#12]
Add a link to LinkedIn profile cos it explains your projects better and u have some articles there!
Maybe even separate links for each?

**Comment by KetanParmar02** [comment]
Hey, @MizouziE I am interested in this issue..
please assign to me this issue.

**Comment by KetanParmar02** [comment]
So, what should I do next please suggest me?

**Comment by MizouziE** [comment]
Sorry @KetanParmar02 , this is actually a redundant issue as I took this in a completely new direction recently. I never expected any interest in my personal portfolio site so didn't do any "housekeeping" when it came to the issues cos I just used them like a notepad to track my ideas.

Appreciate the other all the same!
